# Twitter creds
CONSUMER_KEY = ''
CONSUMER_SECRET = ''
ACCESS_TOKEN = ''
ACCESS_TOKEN_SECRET = ''

# Twilio creds
TWILIO_ACCOUNT_SID = ''
TWILIO_AUTH_TOKEN = ''
TWILIO_FROM = ''

# Twilioserver creds
TWILIO_SERVER_SECRET = ''
TWILIO_SERVER_URL = ''
TWILIO_AUTH_TOKEN = ''
